name = "my-tracking-stack-v3"
compatibility_date = "2025-03-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "tracking-db"
database_id = "b7d1c135-295a-4cdb-8ee8-2c918193127c"
